// Schema is generated by the build agent during Phase 2.
//
// Auth tables (user, session, account, verification) are added by:
//   npx @better-auth/cli generate
//
// Product-specific tables are appended here by the build agent
// based on the inspected PRD and build-spec.md.
