#!/bin/bash
# ralph/harden-watchdog.sh - Post-parity hardening orchestrator (Phases 4-8)
#
# Usage: ./ralph/harden-watchdog.sh <target-url>

set -euo pipefail
cd "$(dirname "$0")/.."

TARGET_URL="${1:?Usage: $0 <target-url>}"
LOG_FILE="ralph-harden-$(date +%Y%m%d-%H%M%S).log"
GAP_FILE="ralph/harden-gap.json"
RESHAPE_PLAN="ralph/reshape-plan.md"
LEARN_REPORT="ralph/harden-learnings.md"
CANARY_COMMAND="${CANARY_COMMAND:-}"
PRODUCTION_CHECKLIST="ralph/production-checklist.json"
export PRODUCTION_CHECKLIST
HARDEN_MAX_RETRIES="${HARDEN_MAX_RETRIES:-3}"

log() { echo "[$(date '+%H:%M:%S')] $1" | tee -a "$LOG_FILE"; }

# Resolve Python
if command -v uv &>/dev/null; then PY="uv run python3"; else PY="python3"; fi

# --- Phase Checkers ---

audit_done() { [ -s "$GAP_FILE" ]; }
reshape_done() { [ -s "$RESHAPE_PLAN" ]; }
harden_complete() {
  $PY -c "import json; print('true' if all(g.get('passes', False) for g in json.load(open('$GAP_FILE'))) else 'false')" 2>/dev/null || echo "false"
}
remaining_gaps() {
  $PY -c "import json; gaps=json.load(open('$GAP_FILE')); print('\n'.join(g.get('id', '<unknown>') for g in gaps if not g.get('passes', False)))" 2>/dev/null || true
}

# --- Runners ---

run_audit() {
  log "Phase 4: Running AUDIT (gap discovery)..."
  $PY - <<'PY'
import json, os
from pathlib import Path

checklist = Path(os.environ.get("PRODUCTION_CHECKLIST", "ralph/production-checklist.json"))
out = Path("ralph/harden-gap.json")
gaps = json.loads(checklist.read_text()) if checklist.exists() else []
for gap in gaps:
    gap.setdefault("passes", False)
    gap.setdefault("evidence", "Seeded from production readiness checklist; verify against the generated clone.")
    gap.setdefault("verifier", "make check && make test")
out.write_text(json.dumps(gaps, indent=2) + "\n")
PY
  log "Phase 4: Wrote $(remaining_gaps | wc -l | tr -d ' ') audit gaps to $GAP_FILE."
}

run_reshape() {
  log "Phase 5: Running RESHAPE (architecture decisions)..."
  cat > "$RESHAPE_PLAN" <<'EOF'
# Production Reshape Plan

This plan is generated by the harden watchdog as the durable handoff between
audit discovery and hardening execution. Resolve gaps in severity order, keep
changes vertical and verifiable, and only mark a gap `passes: true` after its
`verifier` command succeeds.
EOF
}

run_harden() {
  log "Phase 6: Running HARDEN (gap burn-down)..."
  $PY - <<'PY'
import json, subprocess, sys
from pathlib import Path

path = Path("ralph/harden-gap.json")
gaps = json.loads(path.read_text())
for gap in gaps:
    if gap.get("passes"):
        continue
    verifier = gap.get("verifier")
    if not verifier:
        print(f"BLOCKER {gap.get('id', '<unknown>')}: missing verifier", file=sys.stderr)
        sys.exit(2)
    result = subprocess.run(verifier, shell=True)
    if result.returncode == 0:
        gap["passes"] = True
        gap["last_verified_by"] = verifier
        path.write_text(json.dumps(gaps, indent=2) + "\n")
        print(f"VERIFIED {gap.get('id', '<unknown>')}")
        sys.exit(0)
    print(f"BLOCKER {gap.get('id', '<unknown>')}: verifier failed ({verifier})", file=sys.stderr)
    sys.exit(result.returncode)
print("No remaining gaps")
PY
}

run_canary() {
  log "Phase 7: Running CANARY (rollout)..."
  if [ -z "$CANARY_COMMAND" ]; then
    log "Phase 7: No CANARY_COMMAND configured; skipping deploy and treating local verification as canary evidence."
    return 0
  fi
  log "Phase 7: Verifying canary via $CANARY_COMMAND"
  bash -lc "$CANARY_COMMAND"
}

run_learn() {
  log "Phase 8: Running LEARN (feedback loop)..."
  $PY - <<'PY'
import json
from collections import Counter
from pathlib import Path

gaps_path = Path("ralph/harden-gap.json")
report_path = Path("ralph/harden-learnings.md")
gaps = json.loads(gaps_path.read_text()) if gaps_path.exists() else []
by_kind = Counter(g.get("kind", "unknown") for g in gaps)
by_severity = Counter(g.get("severity", "unknown") for g in gaps)
lines = [
    "# Harden Learnings",
    "",
    "Generated by `ralph/harden-watchdog.sh` after a completed hardening pass.",
    "",
    "## Gap Summary",
    "",
    f"- Total gaps: {len(gaps)}",
    f"- Passed gaps: {sum(1 for g in gaps if g.get('passes'))}",
    "",
    "## By Severity",
    "",
]
lines.extend(f"- {key}: {count}" for key, count in sorted(by_severity.items()))
lines.extend(["", "## By Kind", ""] )
lines.extend(f"- {key}: {count}" for key, count in sorted(by_kind.items()))
lines.extend(["", "## Patterns To Feed Back", ""] )
for gap in gaps:
    if gap.get("passes"):
        lines.append(f"- {gap.get('id')}: keep verifier `{gap.get('last_verified_by') or gap.get('verifier', 'n/a')}` with future templates.")
report_path.write_text("\n".join(lines) + "\n")
PY
  log "Phase 8: Wrote learnings to $LEARN_REPORT."
}

# --- Main Flow ---

log "=== Ralph-to-Ralph: Production Harden Loop Started ==="
log "Target: $TARGET_URL"

# Phase 4: Audit
if ! audit_done; then
  run_audit
fi

# Phase 5: Reshape
if ! reshape_done; then
  run_reshape
fi

# Phase 6: Harden
harden_attempt=0
while [ "$(harden_complete)" != "true" ]; do
  harden_attempt=$((harden_attempt + 1))
  if [ "$harden_attempt" -gt "$HARDEN_MAX_RETRIES" ]; then
    log "Phase 6: BLOCKED after $HARDEN_MAX_RETRIES attempts. Remaining gaps: $(remaining_gaps | paste -sd ', ' -)"
    exit 1
  fi
  run_harden
done

# Phase 7: Canary
run_canary

# Phase 8: Learn
run_learn

log "=== RALPH-TO-RALPH HARDENING COMPLETE ==="
